name:                double-elimination
version:             0.1.0.0
github:              "EgorLappo/double-elimination"
license:             BSD3
author:              "Egor Lappo"
maintainer:          "egor@ccrma.stanford.edu"
copyright:           "2023 Egor Lappo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EgorLappo/double-elimination#readme>

dependencies:
- base >= 4.7 && < 5
- text 
- containers
- array
- random
- mtl
- fgl
- graphviz

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  double-elimination-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - double-elimination

tests:
  double-elimination-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - double-elimination
